import './globals.css'
import './root.css'
import type { Metadata } from 'next'
import { TocCurrentPosProvider } from '@/widgets/toc/TocState'
import { getMeta } from './cache'
import RootHead from '@/components/root_head'
import Root from '@/components/root'
import { Body } from '@/components/body'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const res = getMeta()
  return (
    <html lang="en" suppressHydrationWarning>
      <RootHead />
      <Body res={res}>{children}</Body>
    </html>
  )
}
