import './globals.css'
import './root.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TocCurrentPosProvider } from '@/widgets/toc/TocState'
import { getMeta } from './cache'
import RootHead from '@/components/root_head'
import Root from '@/components/root'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const res = getMeta()
  return (
    <html lang="en" suppressHydrationWarning>
      <RootHead />
      <body className={inter.className}>
        <div id="root">
          <TocCurrentPosProvider meta={res}>
            <Root>{children}</Root>
          </TocCurrentPosProvider>
        </div>
      </body>
    </html>
  )
}
